# Setup the common environment
- name: Get MongoDB Key
  apt_key: 
    keyserver=hkp://keyserver.ubuntu.com:80
    id=7F0CEB10
    state=present

- name: Add MongoDB repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

# - name: Run Tee Command for MongoDB
#   command: tee /etc/apt/sources.list.d/mongodb.list

- name: Add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add repo for nodesource
  apt_repository: repo='deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main' state=present

- name: Update apt cache
  apt: update_cache=yes

- name: Update OS
  apt: upgrade=dist force=yes
