- name: Install Nodejs
  apt: name={{item}} state=latest
  register: result
  with_items:
    - nodejs
    - git

- name: Install Main Node Packages
  npm: name={{item}} global=yes state=latest
  when: result|success
  with_items:
    - coffee-script
    - grunt-cli
    - bower

