--- # Test project 
- hosts: "{{hostname}}"
  remote_user: "{{user}}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars_files:
    - roles/common/files/config_vars.yml
  roles:
    - mean_app